name: CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - name: Install .NET (v5.0)
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Pack
        run: |
          dotnet nuget locals all --clear
          dotnet pack --configuration Release --output pack

      - name: Deploy Nuget
        run: |
          dotnet nuget push .\pack\*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: doc/docfx/docfx.json
        
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/docfx/_site
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'